var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-state borders
		'lakesColor':'#ACE9FC', // lakes color
		'namesColor':'#303030', //color of short names
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ALABAMA', //state hover content
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Alabama-cpa-requirements', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#EBECED', //state's color when page loads
		'overColor':'#008ffe',
		'downColor':'#0061ac',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'ALASKA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Alaska-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_3':{
		'hover': 'ARIZONA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Arizona-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_4':{
		'hover': 'ARKANSAS',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Arkansas-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_5':{
		'hover': 'CALIFORNIA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/California-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_6':{
		'hover': 'COLORADO',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Colorado-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_7':{
		'hover': 'CONNECTICUT',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Connecticut-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_8':{
		'hover': 'DELAWARE',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Delware-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_9':{
		'hover': 'FLORIDA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Florida-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_10':{
		'hover': 'GEORGIA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Georgia-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_11':{
		'hover': 'HAWAII',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Hawaii-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_12':{
		'hover': 'IDAHO',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Idaho-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_13':{
		'hover': 'ILLINOIS',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Illinois-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_14':{
		'hover': 'INDIANA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Indiana-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_15':{
		'hover': 'IOWA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Iowa-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_16':{
		'hover': 'KANSAS',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Kansas-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_17':{
		'hover': 'KENTUCKY',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Kentucky-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_18':{
		'hover': 'LOUISIANA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Louisiana-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_19':{
		'hover': 'MAINE',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Maine-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_20':{
		'hover': 'MARYLAND',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Maryland-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_21':{
		'hover': 'MASSACHUSETTS',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Massachusetts-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_22':{
		'hover': 'MICHIGAN',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Michigan-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_23':{
		'hover': 'MINNESOTA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Minnesota-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_24':{
		'hover': 'MISSISSIPPI',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Mississippi-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_25':{
		'hover': 'MISSOURI',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Missouri-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_26':{
		'hover': 'MONTANA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Montana-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_27':{
		'hover': 'NEBRASKA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Nebraska-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_28':{
		'hover': 'NEVADA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Nevada-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_29':{
		'hover': 'NEW HAMPSHIRE',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/New-Hampshire-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_30':{
		'hover': 'NEW JERSEY',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/New-Jersey-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_31':{
		'hover': 'NEW MEXICO',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/New-Mexico-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_32':{
		'hover': 'NEW YORK',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/New-York-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_33':{
		'hover': 'NORTH CAROLINA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/North-Carolina-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_34':{
		'hover': 'NORTH DAKOTA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/North-Dakota-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_35':{
		'hover': 'OHIO',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Ohio-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_36':{
		'hover': 'OKLAHOMA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Oklahoma-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_37':{
		'hover': 'OREGON',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Oregon-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_38':{
		'hover': 'PENNSYLVANIA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Pennsylvania-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_39':{
		'hover': 'RHODE ISLAND',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Rhode-Island-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_40':{
		'hover': 'SOUTH CAROLINA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/South-Carolina-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_41':{
		'hover': 'SOUTH DAKOTA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/South-Dakota-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_42':{
		'hover': 'TENNESSEE',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Tennessee-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_43':{
		'hover': 'TEXAS',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Texas-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_44':{
		'hover': 'UTAH',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Utah-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_45':{
		'hover': 'VERMONT',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Vermont-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_46':{
		'hover': 'VIRGINIA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Virginia-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_47':{
		'hover': 'WASHINGTON',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Washington-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_48':{
		'hover': 'WEST VIRGINIA',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/West-Virginia-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_49':{
		'hover': 'WISCONSIN',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Wisconsin-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
	'map_50':{
		'hover': 'WYOMING',
		'url':'http://www.cpaexamguide.com/cpa-exam-requirements/Wyoming-cpa-requirements',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#008ffe',
		'downColor':'#0061ac',
		'enable':true,
	},
}
