<?php 
#version : 1.24
if(!defined("THANKSTHRIVE"))die();
$thrive_data = array(
	/* "first_name" => array(
		"label"	=> "First Name",
		"key"	=> "['customer']['first_name']"),
	"last_name" => array(
		"label"	=> "Last Name",
		"key"	=> "['customer']['last_name']"), 
	"email" => array(
		"label"	=> "Email",
		"key"	=> "['customer']['email']"),*/
	"user_name" => array(
		"label"	=> "Username",
		"key"	=> "['user_name']"),
	"password" => array(
		"label"	=> "Password",
		"key"	=> "['password']"),
	"paypal_email" => array(
		"label"	=> "Paypal Email",
		"key"	=> "['paypal_email']"),
	"payment_email" => array(
		"label"	=> "Payment Email",
		"key"	=> "['payment_email']"),
	"referrer" => array(
		"label"	=> "Referrer",
		"key"	=> "['referrer']"),
	"ref" => array(
		"label"	=> "Ref",
		"key"	=> "['ref']"),
	"affiliate_id" => array(
		"label"	=> "Affiliate ID",
		"key"	=> "['affiliate_id']"),
	"thrivecart_account" => array(
		"label"	=> "Thrivecart Account",
		"key"	=> "['thrivecart_account']"),
	"thrivecart_secret" => array(
		"label"	=> "Thrivecart Secret",
		"key"	=> "['thrivecart_secret']"),
	"base_product_id" => array(
		"label"	=> "Base Product ID",
		"key"	=> "['base_product']"),
	"order_id" => array(
		"label"	=> "Order ID",
		"key"	=> "['order_id']"),
	"order_timestamp" => array(
		"label"	=> "Order Timestamp",
		"key"	=> "['order_timestamp']"),
	"currency" => array(
		"label"	=> "Currency",
		"key"	=> "['currency']"),
	"customer_id" => array(
		"label"	=> "Customer ID",
		"key"	=> "['customer_id']"),
	"customer_identifier" => array(
		"label"	=> "Payment Processor ID", //Customer Identifier
		"key"	=> "['customer_identifier']"),
	"stripe_id" => array(
		"label"	=> "Stripe ID",
		"key"	=> "['customer_identifier']"),
	"business_name" => array(
		"label"	=> "Business Name",
		"key"	=> "['customer']['business_name']"),
	"customer_contactno" => array(
		"label"	=> "Customer Contact Number",
		"key"	=> "['customer']['contactno']"),
	"customer_address_country" => array(
		"label"	=> "Customer Address Country",
		"key"	=> "['customer']['address']['country']"),
	"customer_address_state" => array(
		"label"	=> "Customer Address State",
		"key"	=> "['customer']['address']['state']"),
	"customer_address_line1" => array(
		"label"	=> "Customer Address Line1",
		"key"	=> "['customer']['address']['line1']"),
	"customer_address_city" => array(
		"label"	=> "Customer Address City",
		"key"	=> "['customer']['address']['city']"),
	"customer_address_region" => array(
		"label"	=> "Customer Address Region",
		"key"	=> "['customer']['address']['region']"),
	"customer_address_province" => array(
		"label"	=> "Customer Address Province",
		"key"	=> "['customer']['address']['province']"),
	"customer_address_zip" => array(
		"label"	=> "Customer Address Zip",
		"key"	=> "['customer']['address']['zip']"),
	"customer_ip_address" => array(
		"label"	=> "Customer IP Address",
		"key"	=> "['customer']['ip_address']"),
	"geo_city" => array(
		"label"	=> "GEO City",
		"key"	=> "['geo_city']"),
	"geo_region" => array(
		"label"	=> "GEO Region",
		"key"	=> "['geo_region']"),
	"geo_country" => array(
		"label"	=> "GEO Country",
		"key"	=> "['geo_country']"),
	"order_tax" => array(
		"label"	=> "Order Tax",
		"key"	=> "['order']['tax']"),
	"order_tax_type" => array(
		"label"	=> "Order Type",
		"key"	=> "['order']['tax_type']"),
	"order_processor" => array(
		"label"	=> "Order Processor",
		"key"	=> "['order']['processor']"),
	"order_total" => array(
		"label"	=> "Order Total",
		"key"	=> "['order']['total']"),
	"coupon_id" => array(
		"label"	=> "Coupon ID",
		"key"	=> "['coupon_id']"),
	"coupon_code" => array(
		"label"	=> "Coupon Code",
		"key"	=> "['coupon_code']"),
	"coupon_name" => array(
		"label"	=> "Coupon Name",
		"key"	=> "['coupon_name']"),

	);
	
	$deep_data = array(
		"order_lifetime_value" => array(
			"label"	=> "Lifetime Value",
			"key"	=> "['order_lifetime_value']"),
		"total_orders" => array(
			"label"	=> "Total Orders",
			"key"	=> "['total_orders']"),
		"total_products" => array(
			"label"	=> "Total Products",
			"key"	=> "['total_products']"),
		"order_price" => array(// Base Product Price
			"label"	=> "Order Price",
			"key"	=> "['order_price']"),
		"order_date" => array(// Base Product Price
			"label"	=> "Order Date",
			"key"	=> "['order_date']"),
		"order_time" => array(// Base Product Price
			"label"	=> "Order Time",
			"key"	=> "['order_time']"),
		"order_product_count" => array(
			"label"	=> "Order Product Count",
			"key"	=> "['order_product_count']"),
		"order_currency" => array(
			"label"	=> "Order Currency",
			"key"	=> "['order_currency']"),
		"product_name" => array(
			"label"	=> "Product Name",
			"key"	=> "['product_name']"),
		"product_id" => array(
			"label"	=> "Product ID",
			"key"	=> "['product_id']"),
		"product_category" => array(
			"label"	=> "Product Category",
			"key"	=> "['product_category']"),
		
				
		"ctsp_license" => array( // This is for us Only and needs to be removed fo Clients= versions...
			"label"	=> "Custom ThriveCart Page License",
			"key"	=> "['ctsp_license']"),
	);
	
	$system_data = array_merge($thrive_data, $deep_data);
	
	define("CUSTOM_TYPE_LABELS",json_encode(array(
			"Main Product" => "Main Product",
			"Bump" => "Bump",
			"Upsell" => "Upsell",
			"Downsell" => "Downsell"
		)));
?>